//
// File generated by rootcint at Tue Dec 15 16:38:05 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdictsdITIdentificatorDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TIdentificatorDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TIdentificator_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void TIdentificator_Dictionary();
   static void *new_TIdentificator(void *p = 0);
   static void *newArray_TIdentificator(Long_t size, void *p);
   static void delete_TIdentificator(void *p);
   static void deleteArray_TIdentificator(void *p);
   static void destruct_TIdentificator(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TIdentificator*)
   {
      ::TIdentificator *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::TIdentificator),0);
      static ::ROOT::TGenericClassInfo 
         instance("TIdentificator", "include/TIdentificator.h", 34,
                  typeid(::TIdentificator), DefineBehavior(ptr, ptr),
                  0, &TIdentificator_Dictionary, isa_proxy, 0,
                  sizeof(::TIdentificator) );
      instance.SetNew(&new_TIdentificator);
      instance.SetNewArray(&newArray_TIdentificator);
      instance.SetDelete(&delete_TIdentificator);
      instance.SetDeleteArray(&deleteArray_TIdentificator);
      instance.SetDestructor(&destruct_TIdentificator);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TIdentificator*)
   {
      return GenerateInitInstanceLocal((::TIdentificator*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TIdentificator*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void TIdentificator_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::TIdentificator*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_TIdentificator(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TIdentificator : new ::TIdentificator;
   }
   static void *newArray_TIdentificator(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TIdentificator[nElements] : new ::TIdentificator[nElements];
   }
   // Wrapper around operator delete
   static void delete_TIdentificator(void *p) {
      delete ((::TIdentificator*)p);
   }
   static void deleteArray_TIdentificator(void *p) {
      delete [] ((::TIdentificator*)p);
   }
   static void destruct_TIdentificator(void *p) {
      typedef ::TIdentificator current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TIdentificator

/********************************************************
* .dicts/TIdentificatorDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTIdentificatorDict();

extern "C" void G__set_cpp_environmentTIdentificatorDict() {
  G__cpp_reset_tagtableTIdentificatorDict();
}
#include <new>
extern "C" int G__cpp_dllrevTIdentificatorDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TIdentificator */
static int G__TIdentificatorDict_804_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TIdentificator* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TIdentificator((TClasTool*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) TIdentificator((TClasTool*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new TIdentificator[n];
       } else {
         p = new((void*) gvp) TIdentificator[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new TIdentificator;
       } else {
         p = new((void*) gvp) TIdentificator;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TIdentificatorDictLN_TIdentificator));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TIdentificator*) G__getstructoffset())->NEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Betta((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Betta((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Id((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Id((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Charge((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Charge((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Px((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Px((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Py((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Py((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Pz((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Pz((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->X((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Y((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Z((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Z((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->StatCC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->StatSC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->StatDC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->StatEC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Status((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Nphe((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Chi2CC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->CCStatus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->DCStatus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Etot((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Ein((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Eout((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ECStatus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TIdentificator*) G__getstructoffset())->XEC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TIdentificator*) G__getstructoffset())->YEC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TIdentificator*) G__getstructoffset())->ZEC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TIdentificator*) G__getstructoffset())->TimeEC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TIdentificator*) G__getstructoffset())->PathEC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PathSC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->TimeSC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->EdepSC((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->SCStatus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Momentum((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Momentum((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Moment((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Moment((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Mass2((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Mass2((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ThetaLab((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ThetaLab((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PhiLab((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PhiLab((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ThetaVirtLab((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ThetaVirtLab());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PhiVirtLab((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PhiVirtLab());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ThetaPQ((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ThetaPQ((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PhiPQ((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PhiPQ((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->CosThetaPQ((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->CosThetaPQ((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PTrans2PQ((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PTrans2PQ((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PLong2PQ((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PLong2PQ((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->Sector((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->Sector((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Pt2((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Pt2((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Pl2((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Pl2((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PlCM((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PlCM((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PmaxCM((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->PmaxCM());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Q2((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Q2());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->W((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->W());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Nu((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Nu());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Xb((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Xb());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Yb((Bool_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Yb());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ZhPi((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Bool_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->ZhPi((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Zh((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])
, (Double_t) G__double(libp->para[2])));
      break;
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Zh((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Zh((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Xf((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Xf((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Mx2((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->Mx2((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->T((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->T((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->TimeCorr4((Double_t) G__double(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TIdentificator*) G__getstructoffset())->GetCorrectedVert());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((TIdentificator*) G__getstructoffset())->GetCategorization((Int_t) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((TIdentificator*) G__getstructoffset())->GetCategorizationMin((Int_t) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ((TIdentificator*) G__getstructoffset())->GetCategorizationOld((Int_t) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TIdentificator*) G__getstructoffset())->GetCategorization());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TIdentificator*) G__getstructoffset())->PrintCategorization();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TIdentificator*) G__getstructoffset())->PrintCategorization((TString*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidTheta((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidTheta((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidThetaMin());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidThetaMinPiPlus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidFunc((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidFuncPiPlus((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidPhi((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidPhi((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidPhiMin());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidPhiMax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidPhiMinPiPlus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_79(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TIdentificator*) G__getstructoffset())->FidPhiMaxPiPlus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_80(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TIdentificator*) G__getstructoffset())->FidCheckCut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_81(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TIdentificator*) G__getstructoffset())->FidCheckCutPiPlus((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_82(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->FidSector((Int_t) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->FidSector((Int_t) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_83(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->ElecVertTarg());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_84(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TIdentificator*) G__getstructoffset())->ElecVertTarg((Bool_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_85(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TIdentificator*) G__getstructoffset())->PionVertTarg((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_86(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TIdentificator*) G__getstructoffset())->XYZToUVW((TVector3*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TIdentificatorDict_804_0_87(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TIdentificator*) G__getstructoffset())->SampFracCheck());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TIdentificatorDict_804_0_88(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TIdentificator* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TIdentificator(*(TIdentificator*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TIdentificatorDictLN_TIdentificator));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TIdentificator G__TTIdentificator;
static int G__TIdentificatorDict_804_0_89(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TIdentificator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TIdentificator*) (soff+(sizeof(TIdentificator)*i)))->~G__TTIdentificator();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TIdentificator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TIdentificator*) (soff))->~G__TTIdentificator();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TIdentificator */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTIdentificatorDict {
 public:
  G__Sizep2memfuncTIdentificatorDict(): p(&G__Sizep2memfuncTIdentificatorDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTIdentificatorDict::*p)();
};

size_t G__get_sizep2memfuncTIdentificatorDict()
{
  G__Sizep2memfuncTIdentificatorDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTIdentificatorDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTIdentificatorDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TIdentificatorDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TIdentificator */
static void G__setup_memvarTIdentificator(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TIdentificatorDictLN_TIdentificator));
   { TIdentificator *p; p=(TIdentificator*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,1,-1,G__defined_typename("Double_t"),-1,4,"kEbeam=",0,"The energy of incoming electron beam");
   G__memvar_setup((void*)0,100,0,1,-1,G__defined_typename("Double_t"),-1,4,"kMpi=",0,"The mass of the pion");
   G__memvar_setup((void*)0,100,0,1,-1,G__defined_typename("Double_t"),-1,4,"kMprt=",0,"The mass of the proton");
   G__memvar_setup((void*)0,100,0,1,-1,G__defined_typename("Double_t"),-1,4,"kMntr=",0,"The mass of the neutron");
   G__memvar_setup((void*)0,100,0,1,-1,G__defined_typename("Double_t"),-1,4,"kGOOD=",0,"The key for the exceptions (should be improved to avoid it at all !!!)");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TClasTool),-1,-1,4,"fCT=",0,"Pointer to the main ClasTool object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TEVNTClass),-1,-1,4,"fEVNT=",0,"Pointer to the EVNT object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TGSIMClass),-1,-1,4,"fGSIM=",0,"Pointer to the GSIM object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TCCPBClass),-1,-1,4,"fCCPB=",0,"Pointer to the CCPB object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TECPBClass),-1,-1,4,"fECPB=",0,"Pointer to the ECPB object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TSCPBClass),-1,-1,4,"fSCPB=",0,"Pointer to the SCPB object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TDCPBClass),-1,-1,4,"fDCPB=",0,"Pointer to the DCPB object");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TIdentificatorDictLN_TString),-1,-1,4,"fPartIds=",0,"Array with the categories of the particles belonging to an event.");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTIdentificatorDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTIdentificator(void) {
   /* TIdentificator */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TIdentificatorDictLN_TIdentificator));
   G__memfunc_setup("TIdentificator",1433,G__TIdentificatorDict_804_0_1, 105, G__get_linked_tagnum(&G__TIdentificatorDictLN_TIdentificator), -1, 0, 1, 5, 1, 0, "U 'TClasTool' - 0 '0' CT", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NEvent",592,G__TIdentificatorDict_804_0_2, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", "inline", (void*) NULL, 0);
   G__memfunc_setup("Betta",496,G__TIdentificatorDict_804_0_3, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Betta",496,G__TIdentificatorDict_804_0_4, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 - kind", "inline", (void*) NULL, 0);
   G__memfunc_setup("Id",173,G__TIdentificatorDict_804_0_5, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", "inline", (void*) NULL, 0);
   G__memfunc_setup("Charge",586,G__TIdentificatorDict_804_0_6, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", "inline", (void*) NULL, 0);
   G__memfunc_setup("Px",200,G__TIdentificatorDict_804_0_7, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", "inline", (void*) NULL, 0);
   G__memfunc_setup("Py",201,G__TIdentificatorDict_804_0_8, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", "inline", (void*) NULL, 0);
   G__memfunc_setup("Pz",202,G__TIdentificatorDict_804_0_9, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", "inline", (void*) NULL, 0);
   G__memfunc_setup("X",88,G__TIdentificatorDict_804_0_10, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Y",89,G__TIdentificatorDict_804_0_11, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Z",90,G__TIdentificatorDict_804_0_12, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", "inline", (void*) NULL, 0);
   G__memfunc_setup("StatCC",546,G__TIdentificatorDict_804_0_13, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("StatSC",562,G__TIdentificatorDict_804_0_14, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("StatDC",547,G__TIdentificatorDict_804_0_15, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("StatEC",548,G__TIdentificatorDict_804_0_16, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Status",644,G__TIdentificatorDict_804_0_17, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Nphe",395,G__TIdentificatorDict_804_0_18, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Chi2CC",460,G__TIdentificatorDict_804_0_19, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("CCStatus",778,G__TIdentificatorDict_804_0_20, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("DCStatus",779,G__TIdentificatorDict_804_0_21, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Etot",412,G__TIdentificatorDict_804_0_22, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Ein",284,G__TIdentificatorDict_804_0_23, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Eout",413,G__TIdentificatorDict_804_0_24, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("ECStatus",780,G__TIdentificatorDict_804_0_25, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("XEC",224,G__TIdentificatorDict_804_0_26, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline // osoto add", (void*) NULL, 0);
   G__memfunc_setup("YEC",225,G__TIdentificatorDict_804_0_27, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline // osoto add", (void*) NULL, 0);
   G__memfunc_setup("ZEC",226,G__TIdentificatorDict_804_0_28, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline // osoto add", (void*) NULL, 0);
   G__memfunc_setup("TimeEC",535,G__TIdentificatorDict_804_0_29, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline // osoto add", (void*) NULL, 0);
   G__memfunc_setup("PathEC",533,G__TIdentificatorDict_804_0_30, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline // osoto add", (void*) NULL, 0);
   G__memfunc_setup("PathSC",547,G__TIdentificatorDict_804_0_31, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("TimeSC",549,G__TIdentificatorDict_804_0_32, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("EdepSC",532,G__TIdentificatorDict_804_0_33, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("SCStatus",794,G__TIdentificatorDict_804_0_34, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", "inline", (void*) NULL, 0);
   G__memfunc_setup("Momentum",850,G__TIdentificatorDict_804_0_35, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Moment",624,G__TIdentificatorDict_804_0_36, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", "Deprecated", (void*) NULL, 0);
   G__memfunc_setup("Mass2",454,G__TIdentificatorDict_804_0_37, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ThetaLab",773,G__TIdentificatorDict_804_0_38, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PhiLab",560,G__TIdentificatorDict_804_0_39, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ThetaVirtLab",1194,G__TIdentificatorDict_804_0_40, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PhiVirtLab",981,G__TIdentificatorDict_804_0_41, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ThetaPQ",663,G__TIdentificatorDict_804_0_42, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PhiPQ",450,G__TIdentificatorDict_804_0_43, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CosThetaPQ",956,G__TIdentificatorDict_804_0_44, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PTrans2PQ",811,G__TIdentificatorDict_804_0_45, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PLong2PQ",691,G__TIdentificatorDict_804_0_46, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Sector",624,G__TIdentificatorDict_804_0_47, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Pt2",246,G__TIdentificatorDict_804_0_48, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - g - 'Bool_t' 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Pl2",238,G__TIdentificatorDict_804_0_49, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - g - 'Bool_t' 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlCM",332,G__TIdentificatorDict_804_0_50, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - g - 'Bool_t' 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PmaxCM",550,G__TIdentificatorDict_804_0_51, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Q2",131,G__TIdentificatorDict_804_0_52, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("W",87,G__TIdentificatorDict_804_0_53, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Nu",195,G__TIdentificatorDict_804_0_54, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Xb",186,G__TIdentificatorDict_804_0_55, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Yb",187,G__TIdentificatorDict_804_0_56, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ZhPi",379,G__TIdentificatorDict_804_0_57, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - k d - 'Double_t' 0 - Mass "
"g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Zh",194,G__TIdentificatorDict_804_0_58, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - - g - 'Bool_t' 0 '0' - "
"d - 'Double_t' 0 '0.139' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Xf",190,G__TIdentificatorDict_804_0_59, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - g - 'Bool_t' 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Mx2",247,G__TIdentificatorDict_804_0_60, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - g - 'Bool_t' 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("T",84,G__TIdentificatorDict_804_0_61, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - - g - 'Bool_t' 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TimeCorr4",857,G__TIdentificatorDict_804_0_62, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - mass i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCorrectedVert",1628,G__TIdentificatorDict_804_0_63, 85, G__get_linked_tagnum(&G__TIdentificatorDictLN_TVector3), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCategorization",1763,G__TIdentificatorDict_804_0_64, 117, G__get_linked_tagnum(&G__TIdentificatorDictLN_TString), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCategorizationMin",2055,G__TIdentificatorDict_804_0_65, 117, G__get_linked_tagnum(&G__TIdentificatorDictLN_TString), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCategorizationOld",2050,G__TIdentificatorDict_804_0_66, 117, G__get_linked_tagnum(&G__TIdentificatorDictLN_TString), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCategorization",1763,G__TIdentificatorDict_804_0_67, 85, G__get_linked_tagnum(&G__TIdentificatorDictLN_TString), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCategorization",2000,G__TIdentificatorDict_804_0_68, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintCategorization",2000,G__TIdentificatorDict_804_0_69, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TString' - 0 - partIds", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidTheta",777,G__TIdentificatorDict_804_0_70, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidThetaMin",1069,G__TIdentificatorDict_804_0_71, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidThetaMinPiPlus",1674,G__TIdentificatorDict_804_0_72, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidFunc",671,G__TIdentificatorDict_804_0_73, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - side i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidFuncPiPlus",1276,G__TIdentificatorDict_804_0_74, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - side i - 'Int_t' 0 - param "
"i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidPhi",564,G__TIdentificatorDict_804_0_75, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidPhiMin",856,G__TIdentificatorDict_804_0_76, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidPhiMax",858,G__TIdentificatorDict_804_0_77, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidPhiMinPiPlus",1461,G__TIdentificatorDict_804_0_78, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidPhiMaxPiPlus",1463,G__TIdentificatorDict_804_0_79, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidCheckCut",1053,G__TIdentificatorDict_804_0_80, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidCheckCutPiPlus",1658,G__TIdentificatorDict_804_0_81, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FidSector",899,G__TIdentificatorDict_804_0_82, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - k g - 'Bool_t' 0 '0' kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ElecVertTarg",1192,G__TIdentificatorDict_804_0_83, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ElecVertTarg",1192,G__TIdentificatorDict_804_0_84, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - kind", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PionVertTarg",1221,G__TIdentificatorDict_804_0_85, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - k", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("XYZToUVW",720,G__TIdentificatorDict_804_0_86, 85, G__get_linked_tagnum(&G__TIdentificatorDictLN_TVector3), -1, 0, 1, 1, 1, 0, "U 'TVector3' - 0 - xyz", "osoto add", (void*) NULL, 0);
   G__memfunc_setup("SampFracCheck",1259,G__TIdentificatorDict_804_0_87, 103, -1, -1, 0, 0, 1, 1, 0, "", "inline //osoto add ", (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("TIdentificator", 1433, G__TIdentificatorDict_804_0_88, (int) ('i'), G__get_linked_tagnum(&G__TIdentificatorDictLN_TIdentificator), -1, 0, 1, 1, 1, 0, "u 'TIdentificator' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TIdentificator", 1559, G__TIdentificatorDict_804_0_89, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTIdentificatorDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTIdentificatorDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTIdentificatorDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TIdentificatorDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TEVNTClass = { "TEVNTClass" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TECPBClass = { "TECPBClass" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TSCPBClass = { "TSCPBClass" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TDCPBClass = { "TDCPBClass" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TCCPBClass = { "TCCPBClass" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TGSIMClass = { "TGSIMClass" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TClasTool = { "TClasTool" , 99 , -1 };
G__linked_taginfo G__TIdentificatorDictLN_TIdentificator = { "TIdentificator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTIdentificatorDict() {
  G__TIdentificatorDictLN_TString.tagnum = -1 ;
  G__TIdentificatorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__TIdentificatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TIdentificatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TIdentificatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TIdentificatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TIdentificatorDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__TIdentificatorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__TIdentificatorDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__TIdentificatorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TIdentificatorDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TIdentificatorDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TIdentificatorDictLN_TVector3.tagnum = -1 ;
  G__TIdentificatorDictLN_TEVNTClass.tagnum = -1 ;
  G__TIdentificatorDictLN_TECPBClass.tagnum = -1 ;
  G__TIdentificatorDictLN_TSCPBClass.tagnum = -1 ;
  G__TIdentificatorDictLN_TDCPBClass.tagnum = -1 ;
  G__TIdentificatorDictLN_TCCPBClass.tagnum = -1 ;
  G__TIdentificatorDictLN_TGSIMClass.tagnum = -1 ;
  G__TIdentificatorDictLN_TClasTool.tagnum = -1 ;
  G__TIdentificatorDictLN_TIdentificator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTIdentificatorDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TString);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TEVNTClass);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TECPBClass);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TSCPBClass);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TDCPBClass);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TCCPBClass);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TGSIMClass);
   G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TClasTool);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TIdentificatorDictLN_TIdentificator),sizeof(TIdentificator),-1,1280,(char*)NULL,G__setup_memvarTIdentificator,G__setup_memfuncTIdentificator);
}
extern "C" void G__cpp_setupTIdentificatorDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTIdentificatorDict()");
  G__set_cpp_environmentTIdentificatorDict();
  G__cpp_setup_tagtableTIdentificatorDict();

  G__cpp_setup_inheritanceTIdentificatorDict();

  G__cpp_setup_typetableTIdentificatorDict();

  G__cpp_setup_memvarTIdentificatorDict();

  G__cpp_setup_memfuncTIdentificatorDict();
  G__cpp_setup_globalTIdentificatorDict();
  G__cpp_setup_funcTIdentificatorDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTIdentificatorDict();
  return;
}
class G__cpp_setup_initTIdentificatorDict {
  public:
    G__cpp_setup_initTIdentificatorDict() { G__add_setup_func("TIdentificatorDict",(G__incsetup)(&G__cpp_setupTIdentificatorDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTIdentificatorDict() { G__remove_setup_func("TIdentificatorDict"); }
};
G__cpp_setup_initTIdentificatorDict G__cpp_setup_initializerTIdentificatorDict;

