/********************************************************************
* .dicts/TIdentificatorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error .dicts/TIdentificatorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTIdentificatorDict();
extern void G__cpp_setup_inheritanceTIdentificatorDict();
extern void G__cpp_setup_typetableTIdentificatorDict();
extern void G__cpp_setup_memvarTIdentificatorDict();
extern void G__cpp_setup_globalTIdentificatorDict();
extern void G__cpp_setup_memfuncTIdentificatorDict();
extern void G__cpp_setup_funcTIdentificatorDict();
extern void G__set_cpp_environmentTIdentificatorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TIdentificator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TIdentificatorDictLN_TString;
extern G__linked_taginfo G__TIdentificatorDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TIdentificatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TIdentificatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TIdentificatorDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TIdentificatorDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TIdentificatorDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TIdentificatorDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TIdentificatorDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TIdentificatorDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TIdentificatorDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TIdentificatorDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TIdentificatorDictLN_TVector3;
extern G__linked_taginfo G__TIdentificatorDictLN_TEVNTClass;
extern G__linked_taginfo G__TIdentificatorDictLN_TECPBClass;
extern G__linked_taginfo G__TIdentificatorDictLN_TSCPBClass;
extern G__linked_taginfo G__TIdentificatorDictLN_TDCPBClass;
extern G__linked_taginfo G__TIdentificatorDictLN_TCCPBClass;
extern G__linked_taginfo G__TIdentificatorDictLN_TGSIMClass;
extern G__linked_taginfo G__TIdentificatorDictLN_TClasTool;
extern G__linked_taginfo G__TIdentificatorDictLN_TIdentificator;

/* STUB derived class for protected member access */
